package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.38

import (
	"context"

	"go.infratographer.com/load-balancer-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// FindLoadBalancerByID is the resolver for the findLoadBalancerByID field.
func (r *entityResolver) FindLoadBalancerByID(ctx context.Context, id gidx.PrefixedID) (*generated.LoadBalancer, error) {
	return r.client.LoadBalancer.Get(ctx, id)
}

// FindLoadBalancerOriginByID is the resolver for the findLoadBalancerOriginByID field.
func (r *entityResolver) FindLoadBalancerOriginByID(ctx context.Context, id gidx.PrefixedID) (*generated.Origin, error) {
	return r.client.Origin.Get(ctx, id)
}

// FindLoadBalancerPoolByID is the resolver for the findLoadBalancerPoolByID field.
func (r *entityResolver) FindLoadBalancerPoolByID(ctx context.Context, id gidx.PrefixedID) (*generated.Pool, error) {
	return r.client.Pool.Get(ctx, id)
}

// FindLoadBalancerPortByID is the resolver for the findLoadBalancerPortByID field.
func (r *entityResolver) FindLoadBalancerPortByID(ctx context.Context, id gidx.PrefixedID) (*generated.Port, error) {
	return r.client.Port.Get(ctx, id)
}

// FindLoadBalancerProviderByID is the resolver for the findLoadBalancerProviderByID field.
func (r *entityResolver) FindLoadBalancerProviderByID(ctx context.Context, id gidx.PrefixedID) (*generated.Provider, error) {
	return r.client.Provider.Get(ctx, id)
}

// FindLocationByID is the resolver for the findLocationByID field.
func (r *entityResolver) FindLocationByID(ctx context.Context, id gidx.PrefixedID) (*Location, error) {
	return &Location{ID: id}, nil
}

// FindResourceOwnerByID is the resolver for the findResourceOwnerByID field.
func (r *entityResolver) FindResourceOwnerByID(ctx context.Context, id gidx.PrefixedID) (*ResourceOwner, error) {
	return &ResourceOwner{ID: id}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
