// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphapi

import (
	"go.infratographer.com/load-balancer-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// Return response from loadBalancerCreate
type LoadBalancerCreatePayload struct {
	// The created load balancer.
	LoadBalancer *generated.LoadBalancer `json:"loadBalancer"`
}

// Return response from loadBalancerDelete
type LoadBalancerDeletePayload struct {
	// The ID of the deleted load balancer.
	DeletedID *gidx.PrefixedID `json:"deletedID,omitempty"`
}

// Return response from loadBalancerUpdate
type LoadBalancerUpdatePayload struct {
	// The updated load balancer.
	LoadBalancer *generated.LoadBalancer `json:"loadBalancer"`
}
