package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"

	"go.infratographer.com/load-balancer-api/internal/ent/generated"
	"go.infratographer.com/x/gidx"
)

// CreateLoadBalancer is the resolver for the createLoadBalancer field.
func (r *mutationResolver) CreateLoadBalancer(ctx context.Context, input generated.CreateLoadBalancerInput) (*generated.LoadBalancer, error) {
	// TODO: authz check here
	return r.client.LoadBalancer.Create().SetInput(input).Save(ctx)
}

// UpdateLoadBalancer is the resolver for the updateLoadBalancer field.
func (r *mutationResolver) UpdateLoadBalancer(ctx context.Context, id gidx.PrefixedID, input generated.UpdateLoadBalancerInput) (*generated.LoadBalancer, error) {
	// TODO: authz check here
	lb, err := r.client.LoadBalancer.Get(ctx, id)
	if err != nil {
		return nil, err
	}
	return lb.Update().SetInput(input).Save(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
