package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.36

import (
	"context"

	"go.infratographer.com/load-balancer-api/internal/ent/generated"
	"go.infratographer.com/permissions-api/pkg/permissions"
	"go.infratographer.com/x/gidx"
)

// LoadBalancerOriginCreate is the resolver for the loadBalancerOriginCreate field.
func (r *mutationResolver) LoadBalancerOriginCreate(ctx context.Context, input generated.CreateLoadBalancerOriginInput) (*LoadBalancerOriginCreatePayload, error) {
	if err := permissions.CheckAccess(ctx, input.PoolID, actionLoadBalancerPoolUpdate); err != nil {
		return nil, err
	}

	// check if pool exists
	_, err := r.client.Pool.Get(ctx, input.PoolID)
	if err != nil {
		return nil, err
	}

	origin, err := r.client.Origin.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &LoadBalancerOriginCreatePayload{LoadBalancerOrigin: origin}, nil
}

// LoadBalancerOriginUpdate is the resolver for the loadBalancerOriginUpdate field.
func (r *mutationResolver) LoadBalancerOriginUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateLoadBalancerOriginInput) (*LoadBalancerOriginUpdatePayload, error) {
	origin, err := r.client.Origin.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	if err := permissions.CheckAccess(ctx, origin.PoolID, actionLoadBalancerPoolUpdate); err != nil {
		return nil, err
	}

	origin, err = origin.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &LoadBalancerOriginUpdatePayload{LoadBalancerOrigin: origin}, nil
}

// LoadBalancerOriginDelete is the resolver for the loadBalancerOriginDelete field.
func (r *mutationResolver) LoadBalancerOriginDelete(ctx context.Context, id gidx.PrefixedID) (*LoadBalancerOriginDeletePayload, error) {
	origin, err := r.client.Origin.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	if err := permissions.CheckAccess(ctx, origin.PoolID, actionLoadBalancerPoolUpdate); err != nil {
		return nil, err
	}

	if err := r.client.Origin.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, err
	}

	return &LoadBalancerOriginDeletePayload{DeletedID: id}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
