package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/labstack/gommon/log"
	"go.infratographer.com/load-balancer-api/internal/ent/generated"
	"go.infratographer.com/load-balancer-api/internal/ent/generated/pool"
	"go.infratographer.com/load-balancer-api/internal/ent/generated/predicate"
	"go.infratographer.com/x/gidx"
)

// PoolCreate is the resolver for the poolCreate field.
func (r *mutationResolver) PoolCreate(ctx context.Context, input generated.CreateLoadBalancerPoolInput) (*PoolCreatePayload, error) {
	// TODO: authz check here
	pool, err := r.client.Pool.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &PoolCreatePayload{Pool: pool}, nil
}

// PoolUpdate is the resolver for the poolUpdate field.
func (r *mutationResolver) PoolUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateLoadBalancerPoolInput) (*PoolUpdatePayload, error) {
	// TODO: authz check here
	pool, err := r.client.Pool.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	pool, err = pool.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &PoolUpdatePayload{Pool: pool}, nil
}

// PoolDelete is the resolver for the poolDelete field.
func (r *mutationResolver) PoolDelete(ctx context.Context, id gidx.PrefixedID) (*PoolDeletePayload, error) {
	// TODO: return the requestID echo generates or we could use the root trace id
	var (
		err error
		tx  *generated.Tx
	)

	defer func() {
		if err != nil {
			if rerr := tx.Rollback(); rerr != nil {
				log.Error(fmt.Errorf("%w: %v", err, rerr).Error())
			}
		}
	}()

	tx, err = r.client.BeginTx(ctx, &sql.TxOptions{})
	if err != nil {
		return nil, err
	}

	// todo: cleanup pool assigments

	// cleanup origins associated with pool
	_, err = tx.Origin.Delete().Where(predicate.Origin(pool.IDEQ(id))).Exec(ctx)
	if err != nil {
		return nil, err
	}

	// delete pool
	if err = tx.Pool.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, err
	}

	if err = tx.Commit(); err != nil {
		return nil, err
	}

	return &PoolDeletePayload{DeletedID: &id}, nil
}

// LoadBalancerPool is the resolver for the loadBalancerPool field.
func (r *queryResolver) LoadBalancerPool(ctx context.Context, id gidx.PrefixedID) (*generated.Pool, error) {
	return r.client.Pool.Get(ctx, id)
}
