package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"go.infratographer.com/load-balancer-api/internal/ent/generated"
	"go.infratographer.com/permissions-api/pkg/permissions"
	"go.infratographer.com/x/gidx"
)

// LoadBalancerProviderCreate is the resolver for the loadBalancerProviderCreate field.
func (r *mutationResolver) LoadBalancerProviderCreate(ctx context.Context, input generated.CreateLoadBalancerProviderInput) (*LoadBalancerProviderCreatePayload, error) {
	if err := permissions.CheckAccess(ctx, input.OwnerID, actionLoadBalancerProviderCreate); err != nil {
		return nil, err
	}

	p, err := r.client.Provider.Create().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}

	return &LoadBalancerProviderCreatePayload{LoadBalancerProvider: p}, nil
}

// LoadBalancerProviderUpdate is the resolver for the loadBalancerProviderUpdate field.
func (r *mutationResolver) LoadBalancerProviderUpdate(ctx context.Context, id gidx.PrefixedID, input generated.UpdateLoadBalancerProviderInput) (*LoadBalancerProviderUpdatePayload, error) {
	if err := permissions.CheckAccess(ctx, id, actionLoadBalancerProviderUpdate); err != nil {
		return nil, err
	}

	p, err := r.client.Provider.Get(ctx, id)
	if err != nil {
		return nil, err
	}

	p, err = p.Update().SetInput(input).Save(ctx)
	if err != nil {
		return nil, err
	}
	return &LoadBalancerProviderUpdatePayload{LoadBalancerProvider: p}, nil
}

// LoadBalancerProviderDelete is the resolver for the loadBalancerProviderDelete field.
func (r *mutationResolver) LoadBalancerProviderDelete(ctx context.Context, id gidx.PrefixedID) (*LoadBalancerProviderDeletePayload, error) {
	if err := permissions.CheckAccess(ctx, id, actionLoadBalancerProviderDelete); err != nil {
		return nil, err
	}

	if err := r.client.Provider.DeleteOneID(id).Exec(ctx); err != nil {
		return nil, err
	}

	return &LoadBalancerProviderDeletePayload{DeletedID: id}, nil
}

// LoadBalancerProvider is the resolver for the loadBalancerProvider field.
func (r *queryResolver) LoadBalancerProvider(ctx context.Context, id gidx.PrefixedID) (*generated.Provider, error) {
	if err := permissions.CheckAccess(ctx, id, actionLoadBalancerProviderGet); err != nil {
		return nil, err
	}

	return r.client.Provider.Get(ctx, id)
}
