package graphapi

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"

	"entgo.io/contrib/entgql"
	"go.infratographer.com/x/gidx"

	"go.infratographer.com/load-balancer-api/internal/ent/generated"
	"go.infratographer.com/load-balancer-api/internal/ent/generated/loadbalancer"
	"go.infratographer.com/load-balancer-api/internal/ent/generated/pool"
)

// Tenant is the resolver for the tenant field.
func (r *loadBalancerResolver) Tenant(ctx context.Context, obj *generated.LoadBalancer) (*Tenant, error) {
	return &Tenant{ID: obj.ID}, nil
}

// Tenant is the resolver for the tenant field.
func (r *loadBalancerPoolResolver) Tenant(ctx context.Context, obj *generated.Pool) (*Tenant, error) {
	return &Tenant{ID: obj.ID}, nil
}

// LoadBalancers is the resolver for the loadBalancers field.
func (r *tenantResolver) LoadBalancers(ctx context.Context, obj *Tenant, after *entgql.Cursor[gidx.PrefixedID], first *int, before *entgql.Cursor[gidx.PrefixedID], last *int, orderBy *generated.LoadBalancerOrder, where *generated.LoadBalancerWhereInput) (*generated.LoadBalancerConnection, error) {
	return r.client.LoadBalancer.Query().Where(loadbalancer.TenantID(obj.ID)).Paginate(ctx, after, first, before, last, generated.WithLoadBalancerOrder(orderBy), generated.WithLoadBalancerFilter(where.Filter))
}

// LoadBalancerPools is the resolver for the loadBalancerPools field.
func (r *tenantResolver) LoadBalancerPools(ctx context.Context, obj *Tenant, after *entgql.Cursor[gidx.PrefixedID], first *int, before *entgql.Cursor[gidx.PrefixedID], last *int, orderBy *generated.LoadBalancerPoolOrder, where *generated.LoadBalancerPoolWhereInput) (*generated.LoadBalancerPoolConnection, error) {
	return r.client.Pool.Query().Where(pool.TenantID(obj.ID)).Paginate(ctx, after, first, before, last, generated.WithLoadBalancerPoolOrder(orderBy), generated.WithLoadBalancerPoolFilter(where.Filter))
}

// Tenant returns TenantResolver implementation.
func (r *Resolver) Tenant() TenantResolver { return &tenantResolver{r} }

type tenantResolver struct{ *Resolver }
