// Code generated by SQLBoiler 4.14.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Assignments    string
	Frontends      string
	GooseDBVersion string
	LoadBalancers  string
	Origins        string
	Pools          string
}{
	Assignments:    "assignments",
	Frontends:      "frontends",
	GooseDBVersion: "goose_db_version",
	LoadBalancers:  "load_balancers",
	Origins:        "origins",
	Pools:          "pools",
}
