// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// LoadBalancerStatus is an object representing the database table.
type LoadBalancerStatus struct {
	StatusID       string     `query:"status_id" param:"status_id" boil:"status_id" json:"status_id" toml:"status_id" yaml:"status_id"`
	LoadBalancerID string     `query:"load_balancer_id" param:"load_balancer_id" boil:"load_balancer_id" json:"load_balancer_id" toml:"load_balancer_id" yaml:"load_balancer_id"`
	Namespace      string     `query:"namespace" param:"namespace" boil:"namespace" json:"namespace" toml:"namespace" yaml:"namespace"`
	Source         string     `query:"source" param:"source" boil:"source" json:"source" toml:"source" yaml:"source"`
	Data           types.JSON `query:"data" param:"data" boil:"data" json:"data" toml:"data" yaml:"data"`
	CreatedAt      time.Time  `query:"created_at" param:"created_at" boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time  `query:"updated_at" param:"updated_at" boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *loadBalancerStatusR `query:"-" param:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L loadBalancerStatusL  `query:"-" param:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LoadBalancerStatusColumns = struct {
	StatusID       string
	LoadBalancerID string
	Namespace      string
	Source         string
	Data           string
	CreatedAt      string
	UpdatedAt      string
}{
	StatusID:       "status_id",
	LoadBalancerID: "load_balancer_id",
	Namespace:      "namespace",
	Source:         "source",
	Data:           "data",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var LoadBalancerStatusTableColumns = struct {
	StatusID       string
	LoadBalancerID string
	Namespace      string
	Source         string
	Data           string
	CreatedAt      string
	UpdatedAt      string
}{
	StatusID:       "load_balancer_statuses.status_id",
	LoadBalancerID: "load_balancer_statuses.load_balancer_id",
	Namespace:      "load_balancer_statuses.namespace",
	Source:         "load_balancer_statuses.source",
	Data:           "load_balancer_statuses.data",
	CreatedAt:      "load_balancer_statuses.created_at",
	UpdatedAt:      "load_balancer_statuses.updated_at",
}

// Generated where

var LoadBalancerStatusWhere = struct {
	StatusID       whereHelperstring
	LoadBalancerID whereHelperstring
	Namespace      whereHelperstring
	Source         whereHelperstring
	Data           whereHelpertypes_JSON
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	StatusID:       whereHelperstring{field: "\"load_balancer_statuses\".\"status_id\""},
	LoadBalancerID: whereHelperstring{field: "\"load_balancer_statuses\".\"load_balancer_id\""},
	Namespace:      whereHelperstring{field: "\"load_balancer_statuses\".\"namespace\""},
	Source:         whereHelperstring{field: "\"load_balancer_statuses\".\"source\""},
	Data:           whereHelpertypes_JSON{field: "\"load_balancer_statuses\".\"data\""},
	CreatedAt:      whereHelpertime_Time{field: "\"load_balancer_statuses\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"load_balancer_statuses\".\"updated_at\""},
}

// LoadBalancerStatusRels is where relationship names are stored.
var LoadBalancerStatusRels = struct {
	LoadBalancer string
}{
	LoadBalancer: "LoadBalancer",
}

// loadBalancerStatusR is where relationships are stored.
type loadBalancerStatusR struct {
	LoadBalancer *LoadBalancer `query:"LoadBalancer" param:"LoadBalancer" boil:"LoadBalancer" json:"LoadBalancer" toml:"LoadBalancer" yaml:"LoadBalancer"`
}

// NewStruct creates a new relationship struct
func (*loadBalancerStatusR) NewStruct() *loadBalancerStatusR {
	return &loadBalancerStatusR{}
}

func (r *loadBalancerStatusR) GetLoadBalancer() *LoadBalancer {
	if r == nil {
		return nil
	}
	return r.LoadBalancer
}

// loadBalancerStatusL is where Load methods for each relationship are stored.
type loadBalancerStatusL struct{}

var (
	loadBalancerStatusAllColumns            = []string{"status_id", "load_balancer_id", "namespace", "source", "data", "created_at", "updated_at"}
	loadBalancerStatusColumnsWithoutDefault = []string{"load_balancer_id", "namespace", "source", "data"}
	loadBalancerStatusColumnsWithDefault    = []string{"status_id", "created_at", "updated_at"}
	loadBalancerStatusPrimaryKeyColumns     = []string{"status_id"}
	loadBalancerStatusGeneratedColumns      = []string{}
)

type (
	// LoadBalancerStatusSlice is an alias for a slice of pointers to LoadBalancerStatus.
	// This should almost always be used instead of []LoadBalancerStatus.
	LoadBalancerStatusSlice []*LoadBalancerStatus
	// LoadBalancerStatusHook is the signature for custom LoadBalancerStatus hook methods
	LoadBalancerStatusHook func(context.Context, boil.ContextExecutor, *LoadBalancerStatus) error

	loadBalancerStatusQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	loadBalancerStatusType                 = reflect.TypeOf(&LoadBalancerStatus{})
	loadBalancerStatusMapping              = queries.MakeStructMapping(loadBalancerStatusType)
	loadBalancerStatusPrimaryKeyMapping, _ = queries.BindMapping(loadBalancerStatusType, loadBalancerStatusMapping, loadBalancerStatusPrimaryKeyColumns)
	loadBalancerStatusInsertCacheMut       sync.RWMutex
	loadBalancerStatusInsertCache          = make(map[string]insertCache)
	loadBalancerStatusUpdateCacheMut       sync.RWMutex
	loadBalancerStatusUpdateCache          = make(map[string]updateCache)
	loadBalancerStatusUpsertCacheMut       sync.RWMutex
	loadBalancerStatusUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var loadBalancerStatusAfterSelectHooks []LoadBalancerStatusHook

var loadBalancerStatusBeforeInsertHooks []LoadBalancerStatusHook
var loadBalancerStatusAfterInsertHooks []LoadBalancerStatusHook

var loadBalancerStatusBeforeUpdateHooks []LoadBalancerStatusHook
var loadBalancerStatusAfterUpdateHooks []LoadBalancerStatusHook

var loadBalancerStatusBeforeDeleteHooks []LoadBalancerStatusHook
var loadBalancerStatusAfterDeleteHooks []LoadBalancerStatusHook

var loadBalancerStatusBeforeUpsertHooks []LoadBalancerStatusHook
var loadBalancerStatusAfterUpsertHooks []LoadBalancerStatusHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *LoadBalancerStatus) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *LoadBalancerStatus) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *LoadBalancerStatus) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *LoadBalancerStatus) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *LoadBalancerStatus) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *LoadBalancerStatus) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *LoadBalancerStatus) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *LoadBalancerStatus) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *LoadBalancerStatus) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancerStatusAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddLoadBalancerStatusHook registers your hook function for all future operations.
func AddLoadBalancerStatusHook(hookPoint boil.HookPoint, loadBalancerStatusHook LoadBalancerStatusHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		loadBalancerStatusAfterSelectHooks = append(loadBalancerStatusAfterSelectHooks, loadBalancerStatusHook)
	case boil.BeforeInsertHook:
		loadBalancerStatusBeforeInsertHooks = append(loadBalancerStatusBeforeInsertHooks, loadBalancerStatusHook)
	case boil.AfterInsertHook:
		loadBalancerStatusAfterInsertHooks = append(loadBalancerStatusAfterInsertHooks, loadBalancerStatusHook)
	case boil.BeforeUpdateHook:
		loadBalancerStatusBeforeUpdateHooks = append(loadBalancerStatusBeforeUpdateHooks, loadBalancerStatusHook)
	case boil.AfterUpdateHook:
		loadBalancerStatusAfterUpdateHooks = append(loadBalancerStatusAfterUpdateHooks, loadBalancerStatusHook)
	case boil.BeforeDeleteHook:
		loadBalancerStatusBeforeDeleteHooks = append(loadBalancerStatusBeforeDeleteHooks, loadBalancerStatusHook)
	case boil.AfterDeleteHook:
		loadBalancerStatusAfterDeleteHooks = append(loadBalancerStatusAfterDeleteHooks, loadBalancerStatusHook)
	case boil.BeforeUpsertHook:
		loadBalancerStatusBeforeUpsertHooks = append(loadBalancerStatusBeforeUpsertHooks, loadBalancerStatusHook)
	case boil.AfterUpsertHook:
		loadBalancerStatusAfterUpsertHooks = append(loadBalancerStatusAfterUpsertHooks, loadBalancerStatusHook)
	}
}

// One returns a single loadBalancerStatus record from the query.
func (q loadBalancerStatusQuery) One(ctx context.Context, exec boil.ContextExecutor) (*LoadBalancerStatus, error) {
	o := &LoadBalancerStatus{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to execute a one query for load_balancer_statuses")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all LoadBalancerStatus records from the query.
func (q loadBalancerStatusQuery) All(ctx context.Context, exec boil.ContextExecutor) (LoadBalancerStatusSlice, error) {
	var o []*LoadBalancerStatus

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to LoadBalancerStatus slice")
	}

	if len(loadBalancerStatusAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all LoadBalancerStatus records in the query.
func (q loadBalancerStatusQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count load_balancer_statuses rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q loadBalancerStatusQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if load_balancer_statuses exists")
	}

	return count > 0, nil
}

// LoadBalancer pointed to by the foreign key.
func (o *LoadBalancerStatus) LoadBalancer(mods ...qm.QueryMod) loadBalancerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"load_balancer_id\" = ?", o.LoadBalancerID),
	}

	queryMods = append(queryMods, mods...)

	return LoadBalancers(queryMods...)
}

// LoadLoadBalancer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (loadBalancerStatusL) LoadLoadBalancer(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLoadBalancerStatus interface{}, mods queries.Applicator) error {
	var slice []*LoadBalancerStatus
	var object *LoadBalancerStatus

	if singular {
		var ok bool
		object, ok = maybeLoadBalancerStatus.(*LoadBalancerStatus)
		if !ok {
			object = new(LoadBalancerStatus)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeLoadBalancerStatus)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeLoadBalancerStatus))
			}
		}
	} else {
		s, ok := maybeLoadBalancerStatus.(*[]*LoadBalancerStatus)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeLoadBalancerStatus)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeLoadBalancerStatus))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &loadBalancerStatusR{}
		}
		args = append(args, object.LoadBalancerID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &loadBalancerStatusR{}
			}

			for _, a := range args {
				if a == obj.LoadBalancerID {
					continue Outer
				}
			}

			args = append(args, obj.LoadBalancerID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`load_balancers`),
		qm.WhereIn(`load_balancers.load_balancer_id in ?`, args...),
		qmhelper.WhereIsNull(`load_balancers.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load LoadBalancer")
	}

	var resultSlice []*LoadBalancer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice LoadBalancer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for load_balancers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for load_balancers")
	}

	if len(loadBalancerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.LoadBalancer = foreign
		if foreign.R == nil {
			foreign.R = &loadBalancerR{}
		}
		foreign.R.LoadBalancerStatuses = append(foreign.R.LoadBalancerStatuses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LoadBalancerID == foreign.LoadBalancerID {
				local.R.LoadBalancer = foreign
				if foreign.R == nil {
					foreign.R = &loadBalancerR{}
				}
				foreign.R.LoadBalancerStatuses = append(foreign.R.LoadBalancerStatuses, local)
				break
			}
		}
	}

	return nil
}

// SetLoadBalancer of the loadBalancerStatus to the related item.
// Sets o.R.LoadBalancer to related.
// Adds o to related.R.LoadBalancerStatuses.
func (o *LoadBalancerStatus) SetLoadBalancer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *LoadBalancer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"load_balancer_statuses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"load_balancer_id"}),
		strmangle.WhereClause("\"", "\"", 2, loadBalancerStatusPrimaryKeyColumns),
	)
	values := []interface{}{related.LoadBalancerID, o.StatusID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LoadBalancerID = related.LoadBalancerID
	if o.R == nil {
		o.R = &loadBalancerStatusR{
			LoadBalancer: related,
		}
	} else {
		o.R.LoadBalancer = related
	}

	if related.R == nil {
		related.R = &loadBalancerR{
			LoadBalancerStatuses: LoadBalancerStatusSlice{o},
		}
	} else {
		related.R.LoadBalancerStatuses = append(related.R.LoadBalancerStatuses, o)
	}

	return nil
}

// LoadBalancerStatuses retrieves all the records using an executor.
func LoadBalancerStatuses(mods ...qm.QueryMod) loadBalancerStatusQuery {
	mods = append(mods, qm.From("\"load_balancer_statuses\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"load_balancer_statuses\".*"})
	}

	return loadBalancerStatusQuery{q}
}

// FindLoadBalancerStatus retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLoadBalancerStatus(ctx context.Context, exec boil.ContextExecutor, statusID string, selectCols ...string) (*LoadBalancerStatus, error) {
	loadBalancerStatusObj := &LoadBalancerStatus{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"load_balancer_statuses\" where \"status_id\"=$1", sel,
	)

	q := queries.Raw(query, statusID)

	err := q.Bind(ctx, exec, loadBalancerStatusObj)
	if err != nil {
		return nil, errors.Wrap(err, "models: unable to select from load_balancer_statuses")
	}

	if err = loadBalancerStatusObj.doAfterSelectHooks(ctx, exec); err != nil {
		return loadBalancerStatusObj, err
	}

	return loadBalancerStatusObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *LoadBalancerStatus) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no load_balancer_statuses provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(loadBalancerStatusColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	loadBalancerStatusInsertCacheMut.RLock()
	cache, cached := loadBalancerStatusInsertCache[key]
	loadBalancerStatusInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			loadBalancerStatusAllColumns,
			loadBalancerStatusColumnsWithDefault,
			loadBalancerStatusColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(loadBalancerStatusType, loadBalancerStatusMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(loadBalancerStatusType, loadBalancerStatusMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"load_balancer_statuses\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"load_balancer_statuses\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into load_balancer_statuses")
	}

	if !cached {
		loadBalancerStatusInsertCacheMut.Lock()
		loadBalancerStatusInsertCache[key] = cache
		loadBalancerStatusInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the LoadBalancerStatus.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *LoadBalancerStatus) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	loadBalancerStatusUpdateCacheMut.RLock()
	cache, cached := loadBalancerStatusUpdateCache[key]
	loadBalancerStatusUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			loadBalancerStatusAllColumns,
			loadBalancerStatusPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update load_balancer_statuses, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"load_balancer_statuses\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, loadBalancerStatusPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(loadBalancerStatusType, loadBalancerStatusMapping, append(wl, loadBalancerStatusPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update load_balancer_statuses row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for load_balancer_statuses")
	}

	if !cached {
		loadBalancerStatusUpdateCacheMut.Lock()
		loadBalancerStatusUpdateCache[key] = cache
		loadBalancerStatusUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q loadBalancerStatusQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for load_balancer_statuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for load_balancer_statuses")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LoadBalancerStatusSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), loadBalancerStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"load_balancer_statuses\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, loadBalancerStatusPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in loadBalancerStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all loadBalancerStatus")
	}
	return rowsAff, nil
}

// Delete deletes a single LoadBalancerStatus record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *LoadBalancerStatus) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no LoadBalancerStatus provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), loadBalancerStatusPrimaryKeyMapping)
	sql := "DELETE FROM \"load_balancer_statuses\" WHERE \"status_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from load_balancer_statuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for load_balancer_statuses")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q loadBalancerStatusQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no loadBalancerStatusQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from load_balancer_statuses")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for load_balancer_statuses")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LoadBalancerStatusSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(loadBalancerStatusBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), loadBalancerStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"load_balancer_statuses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, loadBalancerStatusPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from loadBalancerStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for load_balancer_statuses")
	}

	if len(loadBalancerStatusAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *LoadBalancerStatus) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLoadBalancerStatus(ctx, exec, o.StatusID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LoadBalancerStatusSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LoadBalancerStatusSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), loadBalancerStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"load_balancer_statuses\".* FROM \"load_balancer_statuses\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, loadBalancerStatusPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in LoadBalancerStatusSlice")
	}

	*o = slice

	return nil
}

// LoadBalancerStatusExists checks if the LoadBalancerStatus row exists.
func LoadBalancerStatusExists(ctx context.Context, exec boil.ContextExecutor, statusID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"load_balancer_statuses\" where \"status_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, statusID)
	}
	row := exec.QueryRowContext(ctx, sql, statusID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if load_balancer_statuses exists")
	}

	return exists, nil
}

// Exists checks if the LoadBalancerStatus row exists.
func (o *LoadBalancerStatus) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return LoadBalancerStatusExists(ctx, exec, o.StatusID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *LoadBalancerStatus) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no load_balancer_statuses provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(loadBalancerStatusColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	loadBalancerStatusUpsertCacheMut.RLock()
	cache, cached := loadBalancerStatusUpsertCache[key]
	loadBalancerStatusUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			loadBalancerStatusAllColumns,
			loadBalancerStatusColumnsWithDefault,
			loadBalancerStatusColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			loadBalancerStatusAllColumns,
			loadBalancerStatusPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert load_balancer_statuses, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(loadBalancerStatusPrimaryKeyColumns))
			copy(conflict, loadBalancerStatusPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryCockroachDB(dialect, "\"load_balancer_statuses\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(loadBalancerStatusType, loadBalancerStatusMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(loadBalancerStatusType, loadBalancerStatusMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		_, _ = fmt.Fprintln(boil.DebugWriter, cache.query)
		_, _ = fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // CockcorachDB doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert load_balancer_statuses")
	}

	if !cached {
		loadBalancerStatusUpsertCacheMut.Lock()
		loadBalancerStatusUpsertCache[key] = cache
		loadBalancerStatusUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
