// Code generated by SQLBoiler 4.14.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// LoadBalancersStatus is an object representing the database table.
type LoadBalancersStatus struct {
	StatusID       string     `query:"status_id" param:"status_id" boil:"status_id" json:"status_id" toml:"status_id" yaml:"status_id"`
	LoadBalancerID string     `query:"load_balancer_id" param:"load_balancer_id" boil:"load_balancer_id" json:"load_balancer_id" toml:"load_balancer_id" yaml:"load_balancer_id"`
	Namespace      string     `query:"namespace" param:"namespace" boil:"namespace" json:"namespace" toml:"namespace" yaml:"namespace"`
	Source         string     `query:"source" param:"source" boil:"source" json:"source" toml:"source" yaml:"source"`
	Data           types.JSON `query:"data" param:"data" boil:"data" json:"data" toml:"data" yaml:"data"`
	CreatedAt      time.Time  `query:"created_at" param:"created_at" boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time  `query:"updated_at" param:"updated_at" boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *loadBalancersStatusR `query:"-" param:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
	L loadBalancersStatusL  `query:"-" param:"-" boil:"-" json:"-" toml:"-" yaml:"-"`
}

var LoadBalancersStatusColumns = struct {
	StatusID       string
	LoadBalancerID string
	Namespace      string
	Source         string
	Data           string
	CreatedAt      string
	UpdatedAt      string
}{
	StatusID:       "status_id",
	LoadBalancerID: "load_balancer_id",
	Namespace:      "namespace",
	Source:         "source",
	Data:           "data",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var LoadBalancersStatusTableColumns = struct {
	StatusID       string
	LoadBalancerID string
	Namespace      string
	Source         string
	Data           string
	CreatedAt      string
	UpdatedAt      string
}{
	StatusID:       "load_balancers_status.status_id",
	LoadBalancerID: "load_balancers_status.load_balancer_id",
	Namespace:      "load_balancers_status.namespace",
	Source:         "load_balancers_status.source",
	Data:           "load_balancers_status.data",
	CreatedAt:      "load_balancers_status.created_at",
	UpdatedAt:      "load_balancers_status.updated_at",
}

// Generated where

var LoadBalancersStatusWhere = struct {
	StatusID       whereHelperstring
	LoadBalancerID whereHelperstring
	Namespace      whereHelperstring
	Source         whereHelperstring
	Data           whereHelpertypes_JSON
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	StatusID:       whereHelperstring{field: "\"load_balancers_status\".\"status_id\""},
	LoadBalancerID: whereHelperstring{field: "\"load_balancers_status\".\"load_balancer_id\""},
	Namespace:      whereHelperstring{field: "\"load_balancers_status\".\"namespace\""},
	Source:         whereHelperstring{field: "\"load_balancers_status\".\"source\""},
	Data:           whereHelpertypes_JSON{field: "\"load_balancers_status\".\"data\""},
	CreatedAt:      whereHelpertime_Time{field: "\"load_balancers_status\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"load_balancers_status\".\"updated_at\""},
}

// LoadBalancersStatusRels is where relationship names are stored.
var LoadBalancersStatusRels = struct {
	LoadBalancer string
}{
	LoadBalancer: "LoadBalancer",
}

// loadBalancersStatusR is where relationships are stored.
type loadBalancersStatusR struct {
	LoadBalancer *LoadBalancer `query:"LoadBalancer" param:"LoadBalancer" boil:"LoadBalancer" json:"LoadBalancer" toml:"LoadBalancer" yaml:"LoadBalancer"`
}

// NewStruct creates a new relationship struct
func (*loadBalancersStatusR) NewStruct() *loadBalancersStatusR {
	return &loadBalancersStatusR{}
}

func (r *loadBalancersStatusR) GetLoadBalancer() *LoadBalancer {
	if r == nil {
		return nil
	}
	return r.LoadBalancer
}

// loadBalancersStatusL is where Load methods for each relationship are stored.
type loadBalancersStatusL struct{}

var (
	loadBalancersStatusAllColumns            = []string{"status_id", "load_balancer_id", "namespace", "source", "data", "created_at", "updated_at"}
	loadBalancersStatusColumnsWithoutDefault = []string{"load_balancer_id", "namespace", "source", "data"}
	loadBalancersStatusColumnsWithDefault    = []string{"status_id", "created_at", "updated_at"}
	loadBalancersStatusPrimaryKeyColumns     = []string{"status_id"}
	loadBalancersStatusGeneratedColumns      = []string{}
)

type (
	// LoadBalancersStatusSlice is an alias for a slice of pointers to LoadBalancersStatus.
	// This should almost always be used instead of []LoadBalancersStatus.
	LoadBalancersStatusSlice []*LoadBalancersStatus
	// LoadBalancersStatusHook is the signature for custom LoadBalancersStatus hook methods
	LoadBalancersStatusHook func(context.Context, boil.ContextExecutor, *LoadBalancersStatus) error

	loadBalancersStatusQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	loadBalancersStatusType                 = reflect.TypeOf(&LoadBalancersStatus{})
	loadBalancersStatusMapping              = queries.MakeStructMapping(loadBalancersStatusType)
	loadBalancersStatusPrimaryKeyMapping, _ = queries.BindMapping(loadBalancersStatusType, loadBalancersStatusMapping, loadBalancersStatusPrimaryKeyColumns)
	loadBalancersStatusInsertCacheMut       sync.RWMutex
	loadBalancersStatusInsertCache          = make(map[string]insertCache)
	loadBalancersStatusUpdateCacheMut       sync.RWMutex
	loadBalancersStatusUpdateCache          = make(map[string]updateCache)
	loadBalancersStatusUpsertCacheMut       sync.RWMutex
	loadBalancersStatusUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var loadBalancersStatusAfterSelectHooks []LoadBalancersStatusHook

var loadBalancersStatusBeforeInsertHooks []LoadBalancersStatusHook
var loadBalancersStatusAfterInsertHooks []LoadBalancersStatusHook

var loadBalancersStatusBeforeUpdateHooks []LoadBalancersStatusHook
var loadBalancersStatusAfterUpdateHooks []LoadBalancersStatusHook

var loadBalancersStatusBeforeDeleteHooks []LoadBalancersStatusHook
var loadBalancersStatusAfterDeleteHooks []LoadBalancersStatusHook

var loadBalancersStatusBeforeUpsertHooks []LoadBalancersStatusHook
var loadBalancersStatusAfterUpsertHooks []LoadBalancersStatusHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *LoadBalancersStatus) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *LoadBalancersStatus) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *LoadBalancersStatus) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *LoadBalancersStatus) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *LoadBalancersStatus) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *LoadBalancersStatus) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *LoadBalancersStatus) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *LoadBalancersStatus) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *LoadBalancersStatus) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range loadBalancersStatusAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddLoadBalancersStatusHook registers your hook function for all future operations.
func AddLoadBalancersStatusHook(hookPoint boil.HookPoint, loadBalancersStatusHook LoadBalancersStatusHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		loadBalancersStatusAfterSelectHooks = append(loadBalancersStatusAfterSelectHooks, loadBalancersStatusHook)
	case boil.BeforeInsertHook:
		loadBalancersStatusBeforeInsertHooks = append(loadBalancersStatusBeforeInsertHooks, loadBalancersStatusHook)
	case boil.AfterInsertHook:
		loadBalancersStatusAfterInsertHooks = append(loadBalancersStatusAfterInsertHooks, loadBalancersStatusHook)
	case boil.BeforeUpdateHook:
		loadBalancersStatusBeforeUpdateHooks = append(loadBalancersStatusBeforeUpdateHooks, loadBalancersStatusHook)
	case boil.AfterUpdateHook:
		loadBalancersStatusAfterUpdateHooks = append(loadBalancersStatusAfterUpdateHooks, loadBalancersStatusHook)
	case boil.BeforeDeleteHook:
		loadBalancersStatusBeforeDeleteHooks = append(loadBalancersStatusBeforeDeleteHooks, loadBalancersStatusHook)
	case boil.AfterDeleteHook:
		loadBalancersStatusAfterDeleteHooks = append(loadBalancersStatusAfterDeleteHooks, loadBalancersStatusHook)
	case boil.BeforeUpsertHook:
		loadBalancersStatusBeforeUpsertHooks = append(loadBalancersStatusBeforeUpsertHooks, loadBalancersStatusHook)
	case boil.AfterUpsertHook:
		loadBalancersStatusAfterUpsertHooks = append(loadBalancersStatusAfterUpsertHooks, loadBalancersStatusHook)
	}
}

// One returns a single loadBalancersStatus record from the query.
func (q loadBalancersStatusQuery) One(ctx context.Context, exec boil.ContextExecutor) (*LoadBalancersStatus, error) {
	o := &LoadBalancersStatus{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to execute a one query for load_balancers_status")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all LoadBalancersStatus records from the query.
func (q loadBalancersStatusQuery) All(ctx context.Context, exec boil.ContextExecutor) (LoadBalancersStatusSlice, error) {
	var o []*LoadBalancersStatus

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to LoadBalancersStatus slice")
	}

	if len(loadBalancersStatusAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all LoadBalancersStatus records in the query.
func (q loadBalancersStatusQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count load_balancers_status rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q loadBalancersStatusQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if load_balancers_status exists")
	}

	return count > 0, nil
}

// LoadBalancer pointed to by the foreign key.
func (o *LoadBalancersStatus) LoadBalancer(mods ...qm.QueryMod) loadBalancerQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"load_balancer_id\" = ?", o.LoadBalancerID),
	}

	queryMods = append(queryMods, mods...)

	return LoadBalancers(queryMods...)
}

// LoadLoadBalancer allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (loadBalancersStatusL) LoadLoadBalancer(ctx context.Context, e boil.ContextExecutor, singular bool, maybeLoadBalancersStatus interface{}, mods queries.Applicator) error {
	var slice []*LoadBalancersStatus
	var object *LoadBalancersStatus

	if singular {
		var ok bool
		object, ok = maybeLoadBalancersStatus.(*LoadBalancersStatus)
		if !ok {
			object = new(LoadBalancersStatus)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeLoadBalancersStatus)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeLoadBalancersStatus))
			}
		}
	} else {
		s, ok := maybeLoadBalancersStatus.(*[]*LoadBalancersStatus)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeLoadBalancersStatus)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeLoadBalancersStatus))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &loadBalancersStatusR{}
		}
		args = append(args, object.LoadBalancerID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &loadBalancersStatusR{}
			}

			for _, a := range args {
				if a == obj.LoadBalancerID {
					continue Outer
				}
			}

			args = append(args, obj.LoadBalancerID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`load_balancers`),
		qm.WhereIn(`load_balancers.load_balancer_id in ?`, args...),
		qmhelper.WhereIsNull(`load_balancers.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load LoadBalancer")
	}

	var resultSlice []*LoadBalancer
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice LoadBalancer")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for load_balancers")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for load_balancers")
	}

	if len(loadBalancerAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.LoadBalancer = foreign
		if foreign.R == nil {
			foreign.R = &loadBalancerR{}
		}
		foreign.R.LoadBalancersStatuses = append(foreign.R.LoadBalancersStatuses, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.LoadBalancerID == foreign.LoadBalancerID {
				local.R.LoadBalancer = foreign
				if foreign.R == nil {
					foreign.R = &loadBalancerR{}
				}
				foreign.R.LoadBalancersStatuses = append(foreign.R.LoadBalancersStatuses, local)
				break
			}
		}
	}

	return nil
}

// SetLoadBalancer of the loadBalancersStatus to the related item.
// Sets o.R.LoadBalancer to related.
// Adds o to related.R.LoadBalancersStatuses.
func (o *LoadBalancersStatus) SetLoadBalancer(ctx context.Context, exec boil.ContextExecutor, insert bool, related *LoadBalancer) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"load_balancers_status\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"load_balancer_id"}),
		strmangle.WhereClause("\"", "\"", 2, loadBalancersStatusPrimaryKeyColumns),
	)
	values := []interface{}{related.LoadBalancerID, o.StatusID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.LoadBalancerID = related.LoadBalancerID
	if o.R == nil {
		o.R = &loadBalancersStatusR{
			LoadBalancer: related,
		}
	} else {
		o.R.LoadBalancer = related
	}

	if related.R == nil {
		related.R = &loadBalancerR{
			LoadBalancersStatuses: LoadBalancersStatusSlice{o},
		}
	} else {
		related.R.LoadBalancersStatuses = append(related.R.LoadBalancersStatuses, o)
	}

	return nil
}

// LoadBalancersStatuses retrieves all the records using an executor.
func LoadBalancersStatuses(mods ...qm.QueryMod) loadBalancersStatusQuery {
	mods = append(mods, qm.From("\"load_balancers_status\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"load_balancers_status\".*"})
	}

	return loadBalancersStatusQuery{q}
}

// FindLoadBalancersStatus retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindLoadBalancersStatus(ctx context.Context, exec boil.ContextExecutor, statusID string, selectCols ...string) (*LoadBalancersStatus, error) {
	loadBalancersStatusObj := &LoadBalancersStatus{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"load_balancers_status\" where \"status_id\"=$1", sel,
	)

	q := queries.Raw(query, statusID)

	err := q.Bind(ctx, exec, loadBalancersStatusObj)
	if err != nil {
		return nil, errors.Wrap(err, "models: unable to select from load_balancers_status")
	}

	if err = loadBalancersStatusObj.doAfterSelectHooks(ctx, exec); err != nil {
		return loadBalancersStatusObj, err
	}

	return loadBalancersStatusObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *LoadBalancersStatus) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no load_balancers_status provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(loadBalancersStatusColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	loadBalancersStatusInsertCacheMut.RLock()
	cache, cached := loadBalancersStatusInsertCache[key]
	loadBalancersStatusInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			loadBalancersStatusAllColumns,
			loadBalancersStatusColumnsWithDefault,
			loadBalancersStatusColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(loadBalancersStatusType, loadBalancersStatusMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(loadBalancersStatusType, loadBalancersStatusMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"load_balancers_status\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"load_balancers_status\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into load_balancers_status")
	}

	if !cached {
		loadBalancersStatusInsertCacheMut.Lock()
		loadBalancersStatusInsertCache[key] = cache
		loadBalancersStatusInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the LoadBalancersStatus.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *LoadBalancersStatus) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	loadBalancersStatusUpdateCacheMut.RLock()
	cache, cached := loadBalancersStatusUpdateCache[key]
	loadBalancersStatusUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			loadBalancersStatusAllColumns,
			loadBalancersStatusPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update load_balancers_status, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"load_balancers_status\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, loadBalancersStatusPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(loadBalancersStatusType, loadBalancersStatusMapping, append(wl, loadBalancersStatusPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update load_balancers_status row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for load_balancers_status")
	}

	if !cached {
		loadBalancersStatusUpdateCacheMut.Lock()
		loadBalancersStatusUpdateCache[key] = cache
		loadBalancersStatusUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q loadBalancersStatusQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for load_balancers_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for load_balancers_status")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o LoadBalancersStatusSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), loadBalancersStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"load_balancers_status\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, loadBalancersStatusPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in loadBalancersStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all loadBalancersStatus")
	}
	return rowsAff, nil
}

// Delete deletes a single LoadBalancersStatus record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *LoadBalancersStatus) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no LoadBalancersStatus provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), loadBalancersStatusPrimaryKeyMapping)
	sql := "DELETE FROM \"load_balancers_status\" WHERE \"status_id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from load_balancers_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for load_balancers_status")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q loadBalancersStatusQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no loadBalancersStatusQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from load_balancers_status")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for load_balancers_status")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o LoadBalancersStatusSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(loadBalancersStatusBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), loadBalancersStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"load_balancers_status\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, loadBalancersStatusPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from loadBalancersStatus slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for load_balancers_status")
	}

	if len(loadBalancersStatusAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *LoadBalancersStatus) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindLoadBalancersStatus(ctx, exec, o.StatusID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *LoadBalancersStatusSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := LoadBalancersStatusSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), loadBalancersStatusPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"load_balancers_status\".* FROM \"load_balancers_status\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, loadBalancersStatusPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in LoadBalancersStatusSlice")
	}

	*o = slice

	return nil
}

// LoadBalancersStatusExists checks if the LoadBalancersStatus row exists.
func LoadBalancersStatusExists(ctx context.Context, exec boil.ContextExecutor, statusID string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"load_balancers_status\" where \"status_id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, statusID)
	}
	row := exec.QueryRowContext(ctx, sql, statusID)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if load_balancers_status exists")
	}

	return exists, nil
}

// Exists checks if the LoadBalancersStatus row exists.
func (o *LoadBalancersStatus) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return LoadBalancersStatusExists(ctx, exec, o.StatusID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *LoadBalancersStatus) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no load_balancers_status provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(loadBalancersStatusColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	loadBalancersStatusUpsertCacheMut.RLock()
	cache, cached := loadBalancersStatusUpsertCache[key]
	loadBalancersStatusUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			loadBalancersStatusAllColumns,
			loadBalancersStatusColumnsWithDefault,
			loadBalancersStatusColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			loadBalancersStatusAllColumns,
			loadBalancersStatusPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert load_balancers_status, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(loadBalancersStatusPrimaryKeyColumns))
			copy(conflict, loadBalancersStatusPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryCockroachDB(dialect, "\"load_balancers_status\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(loadBalancersStatusType, loadBalancersStatusMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(loadBalancersStatusType, loadBalancersStatusMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		_, _ = fmt.Fprintln(boil.DebugWriter, cache.query)
		_, _ = fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // CockcorachDB doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert load_balancers_status")
	}

	if !cached {
		loadBalancersStatusUpsertCacheMut.Lock()
		loadBalancersStatusUpsertCache[key] = cache
		loadBalancersStatusUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
