apiVersion: v2
name: load-balancer-api
description: A Helm chart to deploy the Infratographer load-balancer-api
type: application
version: 0.0.1
appVersion: "0.0.1"
kubeVersion: ">=1.24"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.1.1
  - name: reloader
    condition: reloader.enabled
    version: "v0.0.124"
    repository: "https://stakater.github.io/stakater-charts"
  - name: cockroachdb
    condition: cockroachdb.enabled
    version: 2.3.1
    repository:  https://helm.equinixmetal.com/
