apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  LOADBALANCERAPI_EVENTS_NATS_URL: "{{ .Values.api.events.nats.url }}"
  LOADBALANCERAPI_EVENTS_NATS_PUBLISHPREFIX: "{{ .Values.api.events.nats.publishPrefix }}"
  LOADBALANCERAPI_EVENTS_NATS_QUEUEGROUP: "{{ .Values.api.events.nats.queueGroup }}"
  LOADBALANCERAPI_EVENTS_NATS_SOURCE: "{{ .Values.api.events.nats.source }}"
  LOADBALANCERAPI_EVENTS_NATS_CONNECTTIMEOUT: "{{ .Values.api.events.nats.connectTimeout }}"
  LOADBALANCERAPI_EVENTS_NATS_SHUTDOWNTIMEOUT: "{{ .Values.api.events.nats.shutdownTimeout }}"
{{- if .Values.api.events.nats.credsSecretName }}
  LOADBALANCERAPI_EVENTS_NATS_CREDSFILE: "{{ .Values.api.events.nats.credsFile }}"
{{- end }}
  LOADBALANCERAPI_METADATA_STATUS_NAMESPACE_ID: "{{ .Values.api.metadata.statusNamespaceID }}"
  LOADBALANCERAPI_OIDC_ENABLED: "{{ .Values.api.oidc.enabled }}"
  LOADBALANCERAPI_OIDC_AUDIENCE: "{{ .Values.api.oidc.audience }}"
  LOADBALANCERAPI_OIDC_ISSUER: "{{ .Values.api.oidc.issuer }}"
  LOADBALANCERAPI_OIDC_JWKS_REMOTE_TIMEOUT: "{{ .Values.api.oidc.jwksRemoteTimeout }}"
  LOADBALANCERAPI_OIDC_CLIENT_ISSUER: "{{ .Values.api.oidc.client.issuer }}"
  LOADBALANCERAPI_PERMISSIONS_IGNORENORESPONDERS: "{{ .Values.api.permissions.ignoreNoResponders }}"
  LOADBALANCERAPI_PERMISSIONS_URL: "{{ .Values.api.permissions.url }}"
  LOADBALANCERAPI_SERVER_LISTEN: ":{{ .Values.api.listenPort }}"
  LOADBALANCERAPI_SERVER_SHUTDOWN_GRACE_PERIOD: "{{ .Values.api.shutdownGracePeriod }}"
  LOADBALANCERAPI_SUPERGRAPH_URL: "{{ .Values.api.supergraph.url }}"
  LOADBALANCERAPI_SUPERGRAPH_TIMEOUT: "{{ .Values.api.supergraph.timeout }}"
{{- if .Values.api.tracing.enabled }}
  LOADBALANCERAPI_TRACING_ENABLED: "{{ .Values.api.tracing.enabled }}"
  LOADBALANCERAPI_TRACING_PROVIDER: "{{ .Values.api.tracing.provider }}"
  LOADBALANCERAPI_TRACING_ENVIRONMENT: "{{ .Values.api.tracing.environment }}"
{{- if eq .Values.api.tracing.provider "jaeger" }}
  LOADBALANCERAPI_TRACING_JAEGER_ENDPOINT: "{{ .Values.api.tracing.jaeger.endpoint }}"
  LOADBALANCERAPI_TRACING_JAEGER_USER: "{{ .Values.api.tracing.jaeger.user }}"
  LOADBALANCERAPI_TRACING_JAEGER_PASSWORD: "{{ .Values.api.tracing.jaeger.password }}"
{{- end }}
{{- if eq .Values.api.tracing.provider "otlpgrpc" }}
  LOADBALANCERAPI_TRACING_OTLP_ENDPOINT: "{{ .Values.api.tracing.otlp.endpoint }}"
  LOADBALANCERAPI_TRACING_OTLP_INSECURE: "{{ .Values.api.tracing.otlp.insecure }}"
  LOADBALANCERAPI_TRACING_OTLP_CERTIFICATE: "{{ .Values.api.tracing.otlp.certificate }}"
{{- end }}
{{- end }}
{{- with .Values.api.trustedProxies }}
  LOADBALANCERAPI_SERVER_TRUSTED_PROXIES: "{{ join " " . }}"
{{- end }}
