apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-config
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
data:
  LOADBALANCERAPI_EVENTS_PUBLISHER_PREFIX: "{{ .Values.api.events.topicPrefix }}"
  LOADBALANCERAPI_EVENTS_PUBLISHER_URL: "{{ .Values.api.events.connectionURL }}"
  LOADBALANCERAPI_OIDC_ENABLED: "{{ .Values.api.oidc.enabled }}"
  LOADBALANCERAPI_OIDC_AUDIENCE: "{{ .Values.api.oidc.audience }}"
  LOADBALANCERAPI_OIDC_ISSUER: "{{ .Values.api.oidc.issuer }}"
  LOADBALANCERAPI_OIDC_JWKS_REMOTE_TIMEOUT: "{{ .Values.api.oidc.jwksRemoteTimeout }}"
  LOADBALANCERAPI_SERVER_LISTEN: ":{{ .Values.api.listenPort }}"
  LOADBALANCERAPI_SERVER_SHUTDOWN_GRACE_PERIOD: "{{ .Values.api.shutdownGracePeriod }}"
  LOADBALANCERAPI_PERMISSIONS_URL: "{{ .Values.api.permissions.url }}"
  LOADBALANCERAPI_TRACING_ENABLED: "{{ .Values.api.tracing.enabled }}"
  LOADBALANCERAPI_TRACING_PROVIDER: "{{ .Values.api.tracing.provider }}"
  LOADBALANCERAPI_TRACING_ENVIRONMENT: "{{ .Values.api.tracing.environment }}"
{{- if eq .Values.api.tracing.provider "jaeger" }}
  LOADBALANCERAPI_TRACING_JAEGER_ENDPOINT: "{{ .Values.api.tracing.jaeger.endpoint }}"
  LOADBALANCERAPI_TRACING_JAEGER_USER: "{{ .Values.api.tracing.jaeger.user }}"
  LOADBALANCERAPI_TRACING_JAEGER_PASSWORD: "{{ .Values.api.tracing.jaeger.password }}"
{{- end }}
{{- if eq .Values.api.tracing.provider "otlpgrpc" }}
  LOADBALANCERAPI_TRACING_OTLP_ENDPOINT: "{{ .Values.api.tracing.otlp.endpoint }}"
  LOADBALANCERAPI_TRACING_OTLP_INSECURE: "{{ .Values.api.tracing.otlp.insecure }}"
  LOADBALANCERAPI_TRACING_OTLP_CERTIFICATE: "{{ .Values.api.tracing.otlp.certificate }}"
{{- end }}
{{- with .Values.api.trustedProxies }}
  LOADBALANCERAPI_SERVER_TRUSTED_PROXIES: "{{ join " " . }}"
{{- end }}
