#!/bin/bash

set -uo pipefail

# Install docker-compose
alias docker-compose='docker compose'
mkdir -p ~/.docker/cli-plugins
curl -sLl https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-linux-x86_64 -o ~/.docker/cli-plugins/docker-compose
chmod +x ~/.docker/cli-plugins/docker-compose
