name: Lint - Helm
on:
  push:
    paths:
      - chart/**
  pull_request:
    paths:
      - chart/**
permissions:
  contents: read
  pull-requests: read
jobs:
  helmci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-helm@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: helm lint
        run: |
          helm lint chart/load-balancer-api/
          helm template chart/load-balancer-api/
